# Generated by Django 3.1.7 on 2021-03-20 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlupperApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category_details',
            old_name='Create_date',
            new_name='create_date',
        ),
        migrations.AlterField(
            model_name='category_details',
            name='event_image',
            field=models.ImageField(blank=True, default='nofile.pdf', null=True, upload_to='Files/'),
        ),
    ]
